//
//  MRTDReadOptions.swift
//  GmrtdKit
//

import Foundation

/// Caller-supplied read configuration. GmrtdKit never reads app settings storage
/// (e.g. UserDefaults) itself — every option that affects how a document is read
/// must be passed in explicitly here.
public struct MRTDReadOptions: Sendable {
    /// Skips PACE authentication and falls back to BAC even when the chip supports PACE.
    public var skipPace: Bool
    /// Skips reading image data groups (e.g. DG2 face image).
    public var skipImages: Bool
    /// Raises the max APDU response length to support extended-length capable chips/readers.
    public var extendedLength: Bool
    /// Whether `.pace` is included in the NFC tag polling option (iOS 16+ only).
    /// Set false to force `.iso14443`-only polling, e.g. for connectivity testing.
    public var includePaceInPolling: Bool

    /// The 8-byte Active Authentication challenge (RND.IFD) to bind this read to.
    ///
    /// **For genuine relay-attack protection, this value must come from whoever will
    /// later verify the evidence — typically your backend, freshly generated per
    /// verification request — not from this device.** A challenge generated by the
    /// same app instance that also captures and stores the AA evidence proves nothing
    /// to a third party: nothing stops that app from generating whatever challenge
    /// happens to match whatever evidence it already captured. Fetch a fresh challenge
    /// from your server before starting the read, pass it here, and send both the
    /// evidence (CBOR) and the same 8 bytes back to your server for verification
    /// (or pass the same bytes into `DocumentJsonRegenerator.regenerate`'s
    /// `aaChallenge` parameter if verification happens on-device).
    ///
    /// If nil, GmrtdKit generates its own random 8-byte challenge locally. This is
    /// enough to bind a read to its own later on-device re-verification/display
    /// (e.g. reopening a saved scan in this app), but provides **no protection**
    /// against captured evidence being replayed to a different, independent
    /// verifier at a later time — only a verifier-issued challenge does that.
    ///
    /// Must be exactly 8 bytes if provided; `MRTDReader.read` fails fast with
    /// `.invalidAAChallenge` (before starting the NFC session) otherwise.
    public var aaChallenge: Data?

    public init(skipPace: Bool = false,
                skipImages: Bool = false,
                extendedLength: Bool = false,
                includePaceInPolling: Bool = true,
                aaChallenge: Data? = nil) {
        self.skipPace = skipPace
        self.skipImages = skipImages
        self.extendedLength = extendedLength
        self.includePaceInPolling = includePaceInPolling
        self.aaChallenge = aaChallenge
    }
}
